import type { Project, Achievement, User } from "./types"

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "Summer Loyalty Campaign",
    description: "Seasonal campaign with tiered rewards for summer purchases",
    status: "active",
    progress: 65,
    teamSize: 4,
    createdAt: "2023-06-15T10:30:00Z",
    updatedAt: "2023-07-20T14:15:00Z",
  },
  {
    id: "proj-2",
    name: "Referral Program",
    description: "Customer referral system with point multipliers",
    status: "active",
    progress: 80,
    teamSize: 3,
    createdAt: "2023-05-10T09:00:00Z",
    updatedAt: "2023-07-18T11:45:00Z",
  },
  {
    id: "proj-3",
    name: "Birthday Rewards",
    description: "Special offers and points for customer birthdays",
    status: "completed",
    progress: 100,
    teamSize: 2,
    createdAt: "2023-03-22T13:20:00Z",
    updatedAt: "2023-06-30T16:10:00Z",
  },
  {
    id: "proj-4",
    name: "VIP Tier Implementation",
    description: "Exclusive benefits for top-tier loyalty members",
    status: "pending",
    progress: 30,
    teamSize: 5,
    createdAt: "2023-07-05T15:45:00Z",
    updatedAt: "2023-07-19T10:30:00Z",
  },
  {
    id: "proj-5",
    name: "Mobile App Integration",
    description: "Connecting loyalty program with the mobile application",
    status: "active",
    progress: 45,
    teamSize: 6,
    createdAt: "2023-06-01T08:15:00Z",
    updatedAt: "2023-07-21T09:20:00Z",
  },
]

export const mockAchievements: Achievement[] = [
  {
    id: "ach-1",
    name: "First Campaign",
    description: "Successfully launch your first loyalty campaign",
    points: 100,
    category: "Basics",
    status: "completed",
    progress: 100,
    completedAt: "2023-06-20T11:30:00Z",
  },
  {
    id: "ach-2",
    name: "Point Master",
    description: "Configure a complex point-earning rule",
    points: 150,
    category: "Advanced",
    status: "in-progress",
    progress: 75,
  },
  {
    id: "ach-3",
    name: "Engagement Pro",
    description: "Achieve 50% customer engagement rate",
    points: 200,
    category: "Engagement",
    status: "in-progress",
    progress: 40,
  },
  {
    id: "ach-4",
    name: "Analytics Guru",
    description: "Generate and analyze 5 different reports",
    points: 175,
    category: "Analytics",
    status: "locked",
    progress: 0,
  },
  {
    id: "ach-5",
    name: "Integration Expert",
    description: "Connect with 3 external services",
    points: 250,
    category: "Technical",
    status: "locked",
    progress: 0,
  },
]

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Alex Johnson",
    email: "alex@example.com",
    role: "admin",
    avatar: "/avatars/alex.jpg",
    createdAt: "2023-01-15T10:30:00Z",
  },
  {
    id: "user-2",
    name: "Sarah Williams",
    email: "sarah@example.com",
    role: "manager",
    avatar: "/avatars/sarah.jpg",
    createdAt: "2023-02-20T14:15:00Z",
  },
  {
    id: "user-3",
    name: "Michael Brown",
    email: "michael@example.com",
    role: "user",
    avatar: "/avatars/michael.jpg",
    createdAt: "2023-03-10T09:45:00Z",
  },
]
