version: '3.8'

services:
  # Kong API Gateway
  kong:
    container_name: dabao-kong
    image: kong:2.8.1
    restart: unless-stopped
    ports:
      - ${KONG_HTTP_PORT}:8000/tcp
      - ${KONG_HTTPS_PORT}:8443/tcp
    volumes:
      # https://github.com/supabase/supabase/issues/12661
      - ./kong/config/kong.yml:/home/kong/temp.yml:ro,z
    # depends_on:
    #   analytics:
    #     condition: service_healthy
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      # https://github.com/supabase/cli/issues/14
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth,rate-limiting,correlation-id,jwt
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      KONG_LOG_LEVEL: debug  # Add debug logging
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
    # Uncomment the entrypoint to ensure proper Kong configuration
    entrypoint: bash -c 'eval "echo \"$$(cat ~/temp.yml)\"" > ~/kong.yml && /docker-entrypoint.sh kong docker-start'


  # analytics:
  #   container_name: dabao-analytics
  #   image: supabase/logflare:1.12.0
  #   restart: unless-stopped
  #   ports:
  #     - 4000:4000
  #   healthcheck:
  #     test: ["CMD", "curl", "http://localhost:4000/health"]
  #     timeout: 5s
  #     interval: 5s
  #     retries: 10
  #   environment:
  #     LOGFLARE_NODE_HOST: 127.0.0.1
  #     DB_USERNAME: ${POSTGRES_USER}
  #     DB_DATABASE: ${POSTGRES_DB}
  #     DB_HOSTNAME: ${POSTGRES_HOST}
  #     DB_PORT: ${POSTGRES_PORT}
  #     DB_PASSWORD: ${POSTGRES_PASSWORD}
  #     DB_SCHEMA: _analytics
  #     LOGFLARE_API_KEY: ${LOGFLARE_API_KEY}
  #     LOGFLARE_SINGLE_TENANT: true
  #     LOGFLARE_SUPABASE_MODE: true
  #     LOGFLARE_MIN_CLUSTER_SIZE: 1
      
  #     # Postgres backend configuration
  #     POSTGRES_BACKEND_URL: ${DATABASE_URL}
  #     POSTGRES_BACKEND_SCHEMA: _analytics
  #     LOGFLARE_FEATURE_FLAG_OVERRIDE: multibackend=true
      
  #     # Add these environment variables to fix replication slot issue
  #     REPLICATION_SLOT: logflare_replication_slot
  #     CREATE_REPLICATION_SLOT: false
  #     WAL_POSITION: "0/0"
  #   networks:
  #     - dabao-network

  # Mail service for development (catches all outgoing emails)
  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - dabao-network


networks:
  dabao-network:
    driver: bridge