_format_version: "2.1"
_transform: true

services:
  - name: client-service
    url: ${CLIENT_SERVICE_URL}
    routes:
      - name: client-route
        paths:
          - /client

  - name: da-assistant-service
    url: ${DA_ASSISTANT_SERVICE_URL}
    routes:
      - name: da-assistant-route
        paths:
          - /assistant

  - name: dabao-mcp-server-service
    url: ${DABAO_MCP_SERVER_SERVICE_URL}
    routes:
      - name: dabao-mcp-server-route
        paths:
          - /mcp

  - name: web-service
    url: ${WEB_SERVICE_URL}
    routes:
      - name: web-route
        paths:
          - /web

  - name: www-service
    url: ${WWW_SERVICE_URL}
    routes:
      - name: www-route
        paths:
          - /

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Content-Type
        - Authorization
      credentials: true
      max_age: 3600