_format_version: "3.0"
_transform: true

# update the host file for locals
services:
  - name: client-service
    url: http://dabao-app-local:3002

  - name: default-service
    url: http://dabao-app-local:3000

routes:

  # 2a) Host-based: *.domain.com → http://localhost:3002
  - name: client-host-route
    service: client-service
    protocols: [ http, https ]
    hosts: [ 'client.dabao-app-local' ]
    strip_path: false
    preserve_host: true

  # 2b) Header-based: X-client-id exists → http://localhost:3002
  - name: client-header-route
    service: client-service
    protocols: [ http, https ]
    headers:
      X-client-id: [ "*" ]
    strip_path: false
    preserve_host: true

  # 3) All other traffic → http://localhost:3000
  - name: default-route
    service: default-service
    protocols: [ http, https ]
    paths: [ / ]
    strip_path: false
    preserve_host: true