_format_version: "3.0"
_transform: true

# update the host file for locals
services:
  - name: dashboard-service
    url: http://dabao-app-local:3001

  - name: client-service
    url: http://dabao-app-local:3002

  - name: default-service
    url: http://dabao-app-local:3000

routes:
  # 1) /dashboard/project/*
  - name: dashboard-route
    service: dashboard-service
    protocols:
      - http
      - https
    paths:
      - /dashboard/project
    strip_path: false

  # 2a) Host-based: *.domain.com
  - name: client-host-route
    service: client-service
    protocols:
      - http
      - https
    hosts:
      - '*.dabao.app'
    strip_path: false

  # 2b) Header-based: any request that has X-client-id
  # Kong will only do exact-value matching here; to match 'any' value we use a catch-all regex.
  - name: client-header-route
    service: client-service
    protocols:
      - http
      - https
    headers:
      X-client-id:
        - ".+"  
    strip_path: false

  # 3) everything else
  - name: default-route
    service: default-service
    protocols:
      - http
      - https
    paths:
      - /  
    strip_path: false
