_format_version: "3.0"

services:
  - name: www-service
    url: "${WWW_SERVICE_URL}"
    host: dabao.in
    port: 80  
    path: / 
    protocol: http
    routes:
      - name: www-route
        paths:
          - /
        strip_path: false
        preserve_host: false
